import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({children}) {
  const session = await getServerSession(authOptions);
  if(!session){
    return redirect('/');
  }
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-blue-200 w-48 p-4">
            aside suff
            <div>
              <Image src={session.user.image} width={64} height={64} alt={'avatar'}/>
            </div>
          </aside>
          <div className="p-6 max-w-4xl mx-auto">
          {children}
        </div>
        </main>
      </body>
    </html>
  );
}
